import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "@/utils/trpc";

const Home: NextPage = () => {
  const { data, error, isLoading } = trpc.useQuery([
    "example.hello",
    { text: "from tRPC" },
  ]);
  if (isLoading) {
    return <p>Loading...</p>;
  }
  if (error) {
    return <p>Error: {error.message}</p>;
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{JSON.stringify(data)}</div>
    </>
  );
};

export default Home;
